; channel
	const_def
	const CHANNEL1 ; 0
	const CHANNEL2 ; 1
	const CHANNEL3 ; 2
	const CHANNEL4 ; 3
DEF NUM_SFX_CHANNELS EQU const_value
	const CHANNEL5 ; 4
	const CHANNEL6 ; 5
	const CHANNEL7 ; 6
	const CHANNEL8 ; 7
DEF NUM_MUSIC_CHANNELS EQU const_value - NUM_SFX_CHANNELS
DEF NUM_CHANNELS EQU const_value

; channelX_struct constants
RSRESET
DEF CHANNEL1_SWEEP     RB ; $00
DEF CHANNEL1_LENGTH    RB ; $01
DEF CHANNEL1_ENVELOPE  RB ; $02
DEF CHANNEL1_FREQUENCY RW ; $03
DEF CHANNEL1_UNUSED    RB ; $05

DEF CHANNEL2_LENGTH    RB ; $06
DEF CHANNEL2_ENVELOPE  RB ; $07
DEF CHANNEL2_FREQUENCY RW ; $08

DEF CHANNEL3_ENABLED   RB ; $0a
DEF CHANNEL3_LENGTH    RB ; $0b
DEF CHANNEL3_LEVEL     RB ; $0c
DEF CHANNEL3_FREQUENCY RW ; $0d
DEF CHANNEL3_UNUSED    RB ; $0f

DEF CHANNEL4_LENGTH    RB ; $10
DEF CHANNEL4_ENVELOPE  RB ; $11
DEF CHANNEL4_FREQUENCY RW ; $12

; generic channel offsets
	const_def
	const CHANNEL_SELECTOR_ENABLED   ; 0
	const CHANNEL_SELECTOR_LENGTH    ; 1
	const CHANNEL_SELECTOR_ENVELOPE  ; 2
	const CHANNEL_SELECTOR_FREQUENCY ; 3

; flags for wSFXActiveChannelFlags
	const_def
	const SFXFLAG_SQUARE1_F ; 0
	const SFXFLAG_SQUARE2_F ; 1
	const_skip
	const SFXFLAG_NOISE_F   ; 3
	const SFXFLAG_WAVE_F    ; 4

DEF SFXFLAG_SQUARE1 EQU 1 << SFXFLAG_SQUARE1_F ; $01
DEF SFXFLAG_SQUARE2 EQU 1 << SFXFLAG_SQUARE2_F ; $02
DEF SFXFLAG_NOISE   EQU 1 << SFXFLAG_NOISE_F   ; $08
DEF SFXFLAG_WAVE    EQU 1 << SFXFLAG_WAVE_F    ; $10

; for wAudioCommandDurations
DEF CHANNEL_OFF EQU 0

DEF VOLUME_SO1_LEVEL EQU %00000111
DEF VOLUME_SO2_LEVEL EQU %01110000
DEF MAX_VOLUME       EQU VOLUME_SO1_LEVEL | VOLUME_SO2_LEVEL

; wWaveSample constants
	const_def
	const WAVEFORM_M_SHAPE ; $0
	const WAVEFORM_SQUARE  ; $1
	const WAVEFORM_SINE    ; $2
DEF NUM_WAVEFORMS EQU const_value

DEF SFX_MINIMUM_PRIORITY EQU 255

DEF PAN_LEFT   EQU %01
DEF PAN_RIGHT  EQU %10
DEF PAN_CENTER EQU %11
