; Boolean checks
DEF FALSE EQU 0
DEF TRUE  EQU 1

DEF NULL EQU $ffff

	const_def
	const VBLANK_0_F ; 0
	const VBLANK_1_F ; 1
	const VBLANK_2_F ; 2
	const VBLANK_3_F ; 3
	const VBLANK_4_F ; 4
	const VBLANK_5_F ; 5
	const VBLANK_6_F ; 6
	const VBLANK_7_F ; 7

DEF VBLANK_0 EQU 1 << VBLANK_0_F
DEF VBLANK_1 EQU 1 << VBLANK_1_F
DEF VBLANK_2 EQU 1 << VBLANK_2_F
DEF VBLANK_3 EQU 1 << VBLANK_3_F
DEF VBLANK_4 EQU 1 << VBLANK_4_F
DEF VBLANK_5 EQU 1 << VBLANK_5_F
DEF VBLANK_6 EQU 1 << VBLANK_6_F
DEF VBLANK_7 EQU 1 << VBLANK_7_F

; wStage constants
	const_def
	const GREEN_GREENS  ; $0
	const CASTLE_LOLOLO ; $1
	const FLOAT_ISLANDS ; $2
	const BUBBLY_CLOUDS ; $3
	const MT_DEDEDE     ; $4
DEF NUM_STAGES EQU const_value
