	const_def
	const MUSIC_BUBBLY_CLOUDS_INTRO ; $00
	const MUSIC_GREEN_GREENS_INTRO  ; $01
	const MUSIC_INVINCIBILITY_CANDY ; $02
	const MUSIC_GAME_OVER           ; $03
	const MUSIC_SPARKLING_STAR      ; $04
	const MUSIC_TITLESCREEN         ; $05
	const MUSIC_FLOAT_ISLANDS_INTRO ; $06
	const MUSIC_LIFE_LOST           ; $07
	const MUSIC_BOSS_BATTLE         ; $08
	const MUSIC_MINT_LEAF           ; $09
	const MUSIC_VICTORY             ; $0a
	const MUSIC_CREDITS             ; $0b
	const MUSIC_CASTLE_LOLOLO_INTRO ; $0c
	const MUSIC_GREEN_GREENS        ; $0d
	const MUSIC_FLOAT_ISLANDS       ; $0e
	const MUSIC_BUBBLY_CLOUDS       ; $0f
	const MUSIC_CASTLE_LOLOLO       ; $10
	const MUSIC_DEDEDE_BATTLE       ; $11
	const MUSIC_MT_DEDEDE           ; $12
DEF NUM_MUSICS EQU const_value
	const_def $ff
	const MUSIC_NONE        ; $ff

	const_def
	const SFX_00 ; $00
	const SFX_INHALE ; $01
	const SFX_02 ; $02
	const SFX_SWALLOW ; $03
	const SFX_JUMP ; $04
	const SFX_BUMP ; $05
	const SFX_DAMAGE ; $06
	const SFX_ENTER_DOOR ; $07
	const SFX_08 ; $08
	const SFX_POWER_UP ; $09
	const SFX_EXPLOSION ; $0a
	const SFX_RESTORE_HP ; $0b
	const SFX_WARP_STAR ; $0c
	const SFX_13 ; $0d
	const SFX_14 ; $0e
	const SFX_15 ; $0f
	const SFX_16 ; $10
	const SFX_17 ; $11
	const SFX_18 ; $12
	const SFX_19 ; $13
	const SFX_20 ; $14
	const SFX_LOSE_LIFE ; $15
	const SFX_1UP ; $16
	const SFX_23 ; $17
	const SFX_PAUSE ; $18
	const SFX_25 ; $19
	const SFX_CURSOR ; $1a
	const SFX_GAME_START ; $1b
	const SFX_28 ; $1c
	const SFX_29 ; $1d
	const SFX_30 ; $1e
	const SFX_31 ; $1f
	const SFX_BOSS_DEFEAT ; $20
DEF NUM_SOUNDCHECK_SFX EQU const_value
	const SFX_33 ; $21
	const SFX_34 ; $22
	const SFX_35 ; $23
DEF NUM_SFX EQU const_value
	const_def $ff
	const SFX_NONE ; $ff
