INCLUDE "macros/asserts.asm"
INCLUDE "macros/constants.asm"
INCLUDE "macros/audio_commands.asm"
INCLUDE "macros/script.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/wram.asm"

INCLUDE "constants/hardware.inc"

INCLUDE "constants/charmaps.asm"
INCLUDE "constants/audio_constants.asm"
INCLUDE "constants/block_constants.asm"
INCLUDE "constants/gfx_constants.asm"
INCLUDE "constants/item_constants.asm"
INCLUDE "constants/kirby_constants.asm"
INCLUDE "constants/menu_constants.asm"
INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/object_constants.asm"
INCLUDE "constants/scene_constants.asm"
INCLUDE "constants/sound_constants.asm"
INCLUDE "constants/stage_constants.asm"

INCLUDE "macros/code.asm"
INCLUDE "macros/coords.asm"
